import {
  View,
  Text,
  FlatList,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
} from "react-native";
import React, { useEffect, useState } from "react";
import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  FieldValue,
  getDocs,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  Unsubscribe,
  where,
} from "firebase/firestore";
import { db } from "../config/firebase";

interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  isEnabled: boolean;
  createdAt?: FieldValue;
}

const ProductsScreent = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Manier om data maar 1 malig op te vragen
  //   useEffect(() => {

  // (async () => {
  //   try {
  //     const q = query(collection(db, "products"));
  //     const qs = await getDocs(q);

  //     const prods = qs.docs.map(
  //       (p) => ({ id: p.id, ...p.data() } as Product)
  //     );

  //     setProducts(prods);
  //   } catch (error) {
  //     console.log(error);
  //   }
  // })();
  //   }, []);

  //   Manier om realtime updates te ontvangen
  useEffect(() => {
    let unsubscribe: Unsubscribe;

    (async () => {
      try {
        const q = query(
          collection(db, "products"),
          where("isEnabled", "==", true),
          where("price", ">", 50),
          orderBy("price", "desc")
        );

        unsubscribe = onSnapshot(q, (qs) => {
          // console.log(qs.docChanges());

          const prods = qs.docs.map(
            (p) => ({ id: p.id, ...p.data() } as Product)
          );
          setProducts(prods);
        });
      } catch (error) {
        console.log(error);
      } finally {
        setIsLoading(false);
      }
    })();

    return () => {
      unsubscribe();
    };
  }, []);

  const handlePress = async () => {
    const newProduct: Omit<Product, "id"> = {
      name: "Web 2 handboek",
      price: 85,
      category: "Boeken",
      isEnabled: true,
      createdAt: serverTimestamp(),
    };

    const updatedProduct: Partial<Omit<Product, "id">> = {
      price: 175,
    };

    try {
      // Manier 1: Nieuw document toevoegen aan de hand van addDoc methode
      // Methode die je gebruikt als de ID autogenerated mag zijn
      //   const collectionRef = collection(db, "products");
      //   await addDoc(collectionRef, newProduct);

      // Manier 2: Nieuw document toevoegen aan de hand van de setDoc methode
      // Methode die je gebruikt als je uw eigen ID wilt geven
      const newId = "web2handboek";
      const docRef = doc(db, `products/${newId}`);

      await setDoc(docRef, newProduct);

      // Manier 3: Updaten van een document aan de hand van de setDoc methode - Overschrijven
      //   await setDoc(docRef, updatedProduct);

      // Manier 4: Updaten van een document aan de hand van de setDoc methode - Niet overschrijven
      //   await setDoc(docRef, updatedProduct, { merge: true });

      // Verwijderen van een document
      //   await deleteDoc(docRef);
    } catch (error) {
      Alert.alert("Fout", "Fout bij het toevoegen van het product!");
    }
  };

  if (isLoading) {
    return (
      <View className="flex-1 justify-center items-center bg-white">
        <ActivityIndicator size="large" />
      </View>
    );
  }

  return (
    <View>
      <FlatList
        data={products}
        renderItem={({ item }) => (
          <View className="flex flex-row justify-between items-center px-4 my-4">
            <Text>{item.name}</Text>
            <Text>{item.price}</Text>
          </View>
        )}
        keyExtractor={(item) => item.id}
      />
      <TouchableOpacity
        className="px-4 py-2 bg-blue-700 mx-4 rounded-lg"
        onPress={handlePress}>
        <Text className="text-center text-white font-bold">
          Product toevoegen
        </Text>
      </TouchableOpacity>
    </View>
  );
};

export default ProductsScreent;
